name: iOS CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Xcode 16.1로 설정
      - name: Set Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app

      # 3. *.xcodeproj 파일 존재하는지 확인
      - name: List files
        run: |
          echo "Current working directory:"
          pwd
          echo "Files in current directory:"
          ls -R

      # 4. Xcode 빌드 및 테스트 실행
      - name: Build and Test
        run: |
          xcodebuild clean build test \
            -project UMC/KREAM/KREAM.xcodeproj \
            -scheme KREAM \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=17.0"
